# workflow for getting Decred VSP data from the decred.org api

name: journal

# Controls when the workflow will run
on:
  schedule:
    - cron: '0 1 * * *' # runs at 01:00 UTC every day

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: execute vsp script # run vsp.py to get the vsp data
        if: always()
        run: python vsp.py
        
      - name: execute node script # run nodes.py to get the node version data
        if: always()
        run: python nodes.py

      - name: execute hashrate script # run hashrate.py to get the hashrate distribution
        if: always()
        run: python hashrate.py

      - name: execute hashrate MPS script # run hashrate.py to get the hashrate distribution
        if: always()
        run: python hashrate-mps.py

      - name: execute dcrlnd script # run hashrate.py to get the hashrate distribution
        if: always()
        run: python dcrln.py

      - name: execute hashrate stream script # run stream_hashDist.py to get the hashrate stream
        if: always()
        run: python stream_hashDist.py

      - name: execute dex script # run dex_decred_org.py to get the hashrate stream
        if: always()
        run: python dex_decred_org.py

      - name: execute dex stream script # run stream_dex_decred_org.py to get the hashrate stream
        if: always()
        run: python stream_dex_decred_org.py

      - name: commit files
        if: always()
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "update data" -a
          
      - name: push changes
        if: always()
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main  
